name: ruznama
description: Ruznama

publish_to: 'none' # Этот проект не публикуется в pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  intl: ^0.20.2
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.5.3
  timelines_plus: ^1.0.7
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
